{% set name = "lomap2" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/Lomap/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2c8ce8cd1af098385830bcaef678a913b672e95142ec4659f9f1a87e46dd1acf

build:
  noarch: python
  number: 0
  entry_points:
    - lomap = lomap.dbmol:startup
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - networkx
    - numpy
    - python >=3.6
    - rdkit

test:
  imports:
    - lomap
  requires:
    - pip
  commands:
    - pip check
    - lomap --help

about:
  home: https://github.com/OpenFreeEnergy/Lomap
  license: MIT
  license_family: MIT
  license_file: LICENCE.txt
  summary: 'Alchemical mutation scoring map'
  description: |
    Lead optimization mapper (LOMAP) is an automated algorithm to plan efficient 
    relative free energy calculations between potential ligands within a 
    substantial of compounds. The original LOMAP code was mainly based 
    on commercial APIs such as OpenEye and Schrodinger. 
    The aim of this project is to develop a new version of LOMAP based on 
    free avalaible APIs such as RDKit offering the scientific community 
    a free tool to plan in advance binding free energy calculations.
  doc_url: https://github.com/OpenFreeEnergy/Lomap
  dev_url: https://github.com/OpenFreeEnergy/Lomap

extra:
  recipe-maintainers:
    - mikemhenry
    - richardjgowers
    - IAlibay
    - dwhswenson
